"""Добавлена модель User

Revision ID: 0047f8ec04ef
Revises: 1ffcd7b3e326
Create Date: 2026-06-17 19:40:24.562647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0047f8ec04ef'
down_revision: Union[str, Sequence[str], None] = '1ffcd7b3e326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
