"""Добавлено is_active таблица News

Revision ID: 1ffcd7b3e326
Revises: ee0abfec9588
Create Date: 2026-06-11 21:25:50.953013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ffcd7b3e326'
down_revision: Union[str, Sequence[str], None] = 'ee0abfec9588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'is_active')
    # ### end Alembic commands ###
