"""Модель User - удалено поле password

Revision ID: 761dc34a0fbb
Revises: d536a4d1007e
Create Date: 2026-06-17 21:10:42.105896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '761dc34a0fbb'
down_revision: Union[str, Sequence[str], None] = 'd536a4d1007e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
