"""Модель User - поле password удалено максимальное количество символов

Revision ID: d536a4d1007e
Revises: f1fd9ae03f09
Create Date: 2026-06-17 20:50:42.538151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd536a4d1007e'
down_revision: Union[str, Sequence[str], None] = 'f1fd9ae03f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
